export const GET_LEADS = 'GET_LEADS';
export const DELETE_LEAD = 'DELETE_LEAD';
export const ADD_LEAD = 'ADD_LEAD';
export const GET_PRODUCTDS = 'GET_PRODUCTDS';
export const DELETE_PRODUCTD = 'DELETE_PRODUCTD';
export const ADD_PRODUCTD = 'ADD_PRODUCTD';

export const GET_HUMANRESOURCES = 'GET_HUMANRESOURCES';
export const DELETE_HUMANRESOURCE = 'DELETE_HUMANRESOURCE';
export const ADD_HUMANRESOURCE = 'ADD_HUMANRESOURCE';

export const GET_PROFITLS = 'GET_PROFITLS';
export const DELETE_PROFITL = 'DELETE_PROFITL';
export const ADD_PROFITL = 'ADD_PROFITL';

export const GET_PRODUCTOS = 'GET_PRODUCTOS';
export const DELETE_PRODUCTO = 'DELETE_PRODUCTO';
export const ADD_PRODUCTO = 'ADD_PRODUCTO';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_MARKETINGS = 'GET_MARKETINGS';
export const DELETE_MARKETING = 'DELETE_MARKETING';
export const ADD_MARKETING = 'ADD_MARKETING';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_LEADS = 'CLEAR_LEADS';
export const CLEAR_MARKETINGS = 'CLEAR_MARKETINGS';
export const CLEAR_CUSTOMERS = 'CLEAR_CUSTOMERS';
export const CLEAR_PRODUCTDS = 'CLEAR_PRODUCTDS';
export const CLEAR_PRODUCTOS = 'CLEAR_PRODUCTOS';
export const CLEAR_HUMANRESOURCES = 'CLEAR_HUMANRESOURCES';
export const CLEAR_PROFITLS = 'CLEAR_PROFITLS';







