# Generated by Django 3.1.2 on 2020-10-15 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_revenue', models.IntegerField(default=0)),
                ('other_revenue', models.IntegerField(default=0)),
                ('professional_service_revenue', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_reaction_time', models.IntegerField(default=0)),
                ('average_resolution_time', models.IntegerField(default=0)),
                ('customer_escalations', models.IntegerField(default=0)),
                ('availability', models.FloatField(default=0.0)),
                ('open_support_tickets', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_frequency', models.IntegerField(default=0)),
                ('estimation_accuracy', models.IntegerField(default=0)),
                ('test_coverage', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_followers', models.IntegerField(default=0)),
                ('website_visitors', models.IntegerField(default=0)),
                ('website_to_lead_ratio', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employees', models.IntegerField(default=0)),
                ('number_of_open_positions', models.IntegerField(default=0)),
                ('time_to_hire', models.IntegerField(default=0)),
                ('attrition', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_promoter_score', models.IntegerField(default=0)),
                ('social_media_followers', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
