# Generated by Django 3.1.2 on 2020-10-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201015_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='created_at',
            field=models.DateField(),
        ),
    ]
