# Generated by Django 3.1.2 on 2020-10-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201015_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='social_media_followers',
            new_name='number_of_customers',
        ),
        migrations.AddField(
            model_name='customers',
            name='net_new_customers',
            field=models.IntegerField(default=0),
        ),
    ]
